#travis configuration for coverage testing
language: c
sudo: required

install:
  - gem install coveralls-lcov
  - sudo apt-get install cmake
  - sudo apt-get install -y lcov

# Compiler selection
compiler:
  - gcc

# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir target && cd target
  - cmake -D CMAKE_BUILD_TYPE=Coverage .. && make && make test && make coverage

after_success:
  - coveralls-lcov ${TRAVIS_BUILD_DIR}/target/coverage/coverage.info
